version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /opt/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    network_mode: host

  matter-server:
    container_name: matter-server
    image: "ghcr.io/home-assistant-libs/python-matter-server:stable"
    volumes:
      - /opt/matter-server/data:/data
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    network_mode: host
    environment:
      - MATTER_SERVER_STORAGE_DIR=/data

  otbr:
    container_name: otbr
    image: "openthread/otbr:latest"
    volumes:
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    network_mode: host
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/ttyACM3:/dev/ttyACM3
    environment:
      - OTBR_AGENT_OPTS="-I wpan0 -B eth0 spinel+hdlc:///dev/ttyACM3"
    entrypoint: ["/usr/sbin/otbr-agent", "-I", "wpan0", "-B", "eth0", "spinel+hdlc:///dev/ttyACM3"]
