version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /opt/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    network_mode: host

  matter-server:
    container_name: matter-server
    image: "ghcr.io/home-assistant-libs/python-matter-server:stable"
    volumes:
      - /opt/matter-server/data:/data
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    network_mode: host
    environment:
      - MATTER_SERVER_STORAGE_DIR=/data

  otbr:
    container_name: otbr
    image: "openthread/otbr:latest"
    # volumes:
    #  - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    network_mode: host
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/ttyACM3:/dev/ttyACM3
    environment:
      - NAT64=0
      - NAT44=0
      - FIREWALL=0
      - DOCKER=0
      - INFRA_IF_NAME=eth0
      - THREAD_IF_NAME=wpan0
    entrypoint: >
      /bin/bash -c "
      /app/script/server &
      sleep 10;
      pkill -f start-stop-daemon;
      /usr/sbin/otbr-agent -I wpan0 -B eth0 -d7 --rest-listen-address 0.0.0.0 --rest-listen-port 8081 spinel+hdlc+uart:///dev/ttyACM3?uart-baudrate=460800\&uart-reset &
      /usr/sbin/otbr-web -I wpan0 -d7 -a 0.0.0.0 -p 8081 &
      sleep infinity"
