#pragma once

#define CHIP_DEVICE_CONFIG_DEVICE_VENDOR_ID 0xFFF1
#define CHIP_DEVICE_CONFIG_DEVICE_PRODUCT_ID 0x8000
#define CHIP_DEVICE_CONFIG_DEVICE_TYPE 0x0101 // On/Off Light
#define CHIP_DEVICE_CONFIG_DEVICE_NAME "CUL32-C6"

#define CHIP_DEVICE_CONFIG_USE_TEST_SETUP_DISCRIMINATOR 3840
#define CHIP_DEVICE_CONFIG_USE_TEST_SETUP_PIN_CODE 20202021

#define CHIP_DEVICE_CONFIG_ENABLE_WIFI_STATION 1
#define CHIP_DEVICE_CONFIG_ENABLE_THREAD 0
#define CHIP_DEVICE_CONFIG_DYNAMIC_ENDPOINT_COUNT 20
